server:
  port: 8082

spring:
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
  application:
    name: offer-service
  config:
    import: "optional:configserver:http://localhost:8888"

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: offer-service
