server:
  port: 8081

spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:http://localhost:8888"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: auth-service
